#!/usr/bin/env python
# -*- coding: utf-8 -*-

import re
import json
import requests


def get_number_of_citations(url):
    headers = {
        "User-Agent": "Jerome's CV updater",
        "From": "jerome.deleon@gmail.com",
    }
    r = requests.get(url, headers=headers)
    try:
        r.raise_for_status()
    except Exception as e:
        print(e)
        return None
    results = re.findall("([0-9,]+) results", r.text)
    if not len(results):
        print("no results found")
        return None
    try:
        return int(results[0].replace(",", ""))
    except Exception as e:
        print(e)
        return None


def update_others():
    fout = "data/other_pubs.json"
    with open(fout, "r") as f:
        pubs = json.load(f)
        for i, pub in enumerate(pubs):
            if not pub["url"].startswith("https://scholar.google.com"):
                continue
            n = get_number_of_citations(pub["url"])
            if n is None or n < pub["citations"]:
                continue
            pubs[i]["citations"] = n

    with open(fout, "w") as f:
        json.dump(pubs, f, sort_keys=True, indent=2, separators=(",", ": "))
    print("Saved: ", fout)

if __name__ == "__main__":
    update_others()
