#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
If run locally, get NASA ADS token from 
https://ui.adsabs.harvard.edu/user/settings/token
save it to a file called ~/.ads/dev_key

If run on GitHub Actions, set the token as a secret called ADS_DEV_KEY
"""
import os
import json
import importlib.util
from operator import itemgetter

import ads
# ads.config.token = 'my token'

# Get the current directory of the script
here = os.path.dirname(os.path.abspath(__file__))
# Import the 'utf8totex' module
spec = importlib.util.spec_from_file_location(
    "utf8totex", os.path.join(here, "utf8totex.py")
)
utf8totex = importlib.util.module_from_spec(spec)
spec.loader.exec_module(utf8totex)

author = "de Leon, J. P."
# exclude papers with asteroid in abstract
search_query = 'aff:"University of Tokyo" database:astronomy -abs:asteroid'

def get_papers(author):
    # Perform an ADS search query to retrieve information about the author's papers
    papers = list(
        ads.SearchQuery(
            q=search_query,
            author=author,
            fl=[
                "id",
                "title",
                "author",
                "doi",
                "year",
                "pubdate",
                "pub",
                "volume",
                "page",
                "identifier",
                "doctype",
                "citation_count",
                "bibcode",
            ],
            max_pages=100,
        )
    )
    dicts = []
    for paper in papers:
        # Process and filter arxiv id
        if paper.identifier is None:
            continue
        aid = [
            ":".join(t.split(":")[1:])
            for t in paper.identifier
            if t.startswith("arXiv:")
        ]
        for t in paper.identifier:
            if len(t.split(".")) != 2:
                continue
            try:
                list(map(int, t.split(".")))
            except ValueError:
                pass
            else:
                aid.append(t)
        try:
            page = int(paper.page[0])
        except (ValueError, TypeError):
            page = None
            if paper.page is not None and paper.page[0].startswith("arXiv:"):
                aid.append(":".join(paper.page[0].split(":")[1:]))
        try:
            # Create a dictionary with relevant paper information
            dicts.append(
                dict(
                    doctype=paper.doctype,
                    authors=list(map(utf8totex.utf8totex, paper.author)),
                    year=paper.year,
                    pubdate=paper.pubdate,
                    doi=paper.doi[0] if paper.doi is not None else None,
                    title=utf8totex.utf8totex(paper.title[0].replace(" &amp; ", " & ")),
                    pub=paper.pub,
                    volume=paper.volume,
                    page=page,
                    arxiv=aid[0] if len(aid) else None,
                    citations=(
                        paper.citation_count if paper.citation_count is not None else 0
                    ),
                    url="https://ui.adsabs.harvard.edu/abs/" + paper.bibcode,
                )
            )
        except Exception as e:
            print(e)
    return sorted(dicts, key=itemgetter("pubdate"), reverse=True)


if __name__ == "__main__":
    papers = get_papers(author)
    fout = "data/pubs.json"
    with open(fout, "w") as f:
        json.dump(papers, f, sort_keys=True, indent=2, separators=(",", ": "))
    print("Saved: ", fout)